# Generated by Django 3.2.3 on 2023-07-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230704_1835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
