# Generated by Django 3.2.3 on 2023-07-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230705_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagrecipes',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
