# Generated by Django 3.2.3 on 2023-07-06 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tagrecipes_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagrecipes',
            name='amount',
        ),
        migrations.AddField(
            model_name='ingridientrecipes',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
