# Generated by Django 3.2.3 on 2023-07-06 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20230706_1303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipes',
            old_name='ingridient',
            new_name='ingredient',
        ),
    ]
