# Generated by Django 3.2.3 on 2023-07-06 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_ingridient_ingredientrecipes_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipes',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.recipes'),
        ),
    ]
